### ISSUE TITLE
Let me crank that soulja boy

### ISSUE THREAD

**Issue by beccasjames** [paultag/PJD5132#1]
When I go to projector.paultag.house/crank-that-soulja-boy the volume on the projector should go **up**. Reroute /crank-that-soulja-boy to the volume `increase` URL plz.

This could be you:
![giphy](https://cloud.githubusercontent.com/assets/8527275/18897496/e9213992-84f8-11e6-9c07-86a7fc38056e.gif)

**Comment by paultag** [comment]
Done with an nginx rule
